[es]
  title = "Candidatos"
  languageName = "EspaÃ±ol"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/es"

#[en]
#  title = "Candidates"
#  languageName = "English"
#  weight = 2
#  languagedir = "ltr"
#  contentdir = "content/en"